[hooks]
pre-commit = "cd authorization_generator && cargo clippy --workspace --all-targets --all-features && cargo +nightly fmt --all -- --check && cd ../request_generator && cargo clippy --workspace --all-targets --all-features && cargo +nightly fmt --all -- --check"

[logging]
verbose = true
